name: Asset checker

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
  schedule:
    - cron: '10 2 * * 3'

jobs:
  assetChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Identify dangling assets
        run: |
          python .github/workflows/check-assets.py
        continue-on-error: false

      - name: Check for dangling_assets file
        id: dangling_assets
        run: |
          if [ -f ./dangling_assets.md ]; then
            echo "Dangling assets file found"
            echo "found=true" >> $GITHUB_ENV
          else
            echo "Dangling assets file not found"
            echo "found=false" >> $GITHUB_ENV
          fi
        continue-on-error: false

      - name: Find existing comment
        id: find_comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: 1  # Replace with your issue number
          comment-author: 'github-actions[bot]'
          body-includes: "Assets report"  # Keyword to identify the comment

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: 1  # Replace with your issue number
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          body-path: ./dangling_assets.md
          edit-mode: replace
        if: env.found == 'true'
