name: Labot checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-and-run:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/digital-work-lab/labot.git
          pip install colrev

      - name: Set Git user name and email
        run: |
          git config --global user.name "Labot"
          git config --global user.email "actions@users.noreply.github.com"
          git config --global url.https://github.com/.insteadOf git://github.com/

      - name: Run labot.repository.main()
        run: |
          python -m labot.repository
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
